# Generated by Django 4.0.3 on 2022-03-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_blogs_alter_registeredusers_registerdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='iitle',
        ),
        migrations.AddField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
