# Generated by Django 4.0.3 on 2022-03-17 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_remove_blogs_iitle_blogs_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='athletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('knockouts', models.IntegerField()),
                ('nickname', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField(default=datetime.date(2022, 3, 17))),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
