# Generated by Django 4.0.3 on 2022-03-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_athletes_news_alter_blogs_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
