# Generated by Django 4.0.3 on 2022-03-28 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_blogs_addedon_alter_blogs_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='athlete2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete2', to='firstapp.athletes'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='addedon',
            field=models.DateField(default=datetime.date(2022, 3, 28)),
        ),
        migrations.AlterField(
            model_name='match',
            name='athlete1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete1', to='firstapp.athletes'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchDate',
            field=models.DateField(default=datetime.date(2022, 3, 28)),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 28)),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='registerDate',
            field=models.DateField(default=datetime.date(2022, 3, 28)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewDate',
            field=models.DateField(default=datetime.date(2022, 3, 28)),
        ),
        migrations.AlterField(
            model_name='stories',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 28)),
        ),
    ]
