# Generated by Django 4.0.3 on 2022-03-29 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_match_athlete2_alter_blogs_addedon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletes',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athletes',
            name='height',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='athletes',
            name='ko',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athletes',
            name='sub',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='athletes',
            name='winstreak',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='twitter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='addedon',
            field=models.DateField(default=datetime.date(2022, 3, 29)),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchDate',
            field=models.DateField(default=datetime.date(2022, 3, 29)),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 29)),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='registerDate',
            field=models.DateField(default=datetime.date(2022, 3, 29)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewDate',
            field=models.DateField(default=datetime.date(2022, 3, 29)),
        ),
        migrations.AlterField(
            model_name='stories',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 29)),
        ),
    ]
