# Generated by Django 4.0.3 on 2022-03-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_remove_match_league_match_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
