# Generated by Django 4.0.3 on 2022-03-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_alter_athletes_instagram_alter_athletes_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletes',
            name='knockouts',
        ),
    ]
