# Generated by Django 4.0.3 on 2022-04-17 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='match',
        ),
        migrations.AddField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='addedon',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchDate',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='registerDate',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewDate',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
        migrations.AlterField(
            model_name='stories',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 17)),
        ),
    ]
