# Generated by Django 4.0.3 on 2022-04-27 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_remove_videos_match_videos_title_alter_blogs_addedon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='videosnew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('video', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogs',
            name='addedon',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchDate',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
        migrations.AlterField(
            model_name='registeredusers',
            name='registerDate',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviewDate',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
        migrations.AlterField(
            model_name='stories',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 27)),
        ),
    ]
