# Generated by Django 4.0.3 on 2022-05-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_alter_blogs_addedon_alter_match_matchdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='match',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.DeleteModel(
            name='stories',
        ),
        migrations.DeleteModel(
            name='answer',
        ),
        migrations.DeleteModel(
            name='gallery',
        ),
        migrations.DeleteModel(
            name='question',
        ),
    ]
