# Generated by Django 4.0.3 on 2022-05-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0026_remove_answer_question_remove_answer_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='videos',
        ),
    ]
